import TopNav from '@/Components/TopNav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className='sticky top-0 z-50'>
        <TopNav/>
      </nav>
        {children}
        </body>
    </html>
  )
}
